/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedOportunidadesRouteImport } from './routes/_authenticated/oportunidades'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedAsistenteRouteImport } from './routes/_authenticated/asistente'
import { Route as AuthenticatedAgendaRouteImport } from './routes/_authenticated/agenda'
import { Route as AuthenticatedClientesIndexRouteImport } from './routes/_authenticated/clientes.index'
import { Route as AuthenticatedAsistenteIndexRouteImport } from './routes/_authenticated/asistente.index'
import { Route as AuthenticatedClientesNuevoRouteImport } from './routes/_authenticated/clientes.nuevo'
import { Route as AuthenticatedClientesImportarRouteImport } from './routes/_authenticated/clientes.importar'
import { Route as AuthenticatedClientesIdRouteImport } from './routes/_authenticated/clientes.$id'
import { Route as AuthenticatedAsistenteThreadIdRouteImport } from './routes/_authenticated/asistente.$threadId'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin.usuarios'
import { Route as AuthenticatedAdminSectoresRouteImport } from './routes/_authenticated/admin.sectores'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOportunidadesRoute =
  AuthenticatedOportunidadesRouteImport.update({
    id: '/oportunidades',
    path: '/oportunidades',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAsistenteRoute = AuthenticatedAsistenteRouteImport.update({
  id: '/asistente',
  path: '/asistente',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgendaRoute = AuthenticatedAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientesIndexRoute =
  AuthenticatedClientesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedClientesRoute,
  } as any)
const AuthenticatedAsistenteIndexRoute =
  AuthenticatedAsistenteIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAsistenteRoute,
  } as any)
const AuthenticatedClientesNuevoRoute =
  AuthenticatedClientesNuevoRouteImport.update({
    id: '/nuevo',
    path: '/nuevo',
    getParentRoute: () => AuthenticatedClientesRoute,
  } as any)
const AuthenticatedClientesImportarRoute =
  AuthenticatedClientesImportarRouteImport.update({
    id: '/importar',
    path: '/importar',
    getParentRoute: () => AuthenticatedClientesRoute,
  } as any)
const AuthenticatedClientesIdRoute = AuthenticatedClientesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedClientesRoute,
} as any)
const AuthenticatedAsistenteThreadIdRoute =
  AuthenticatedAsistenteThreadIdRouteImport.update({
    id: '/$threadId',
    path: '/$threadId',
    getParentRoute: () => AuthenticatedAsistenteRoute,
  } as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/admin/usuarios',
    path: '/admin/usuarios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSectoresRoute =
  AuthenticatedAdminSectoresRouteImport.update({
    id: '/admin/sectores',
    path: '/admin/sectores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/asistente': typeof AuthenticatedAsistenteRouteWithChildren
  '/clientes': typeof AuthenticatedClientesRouteWithChildren
  '/oportunidades': typeof AuthenticatedOportunidadesRoute
  '/api/chat': typeof ApiChatRoute
  '/admin/sectores': typeof AuthenticatedAdminSectoresRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/asistente/$threadId': typeof AuthenticatedAsistenteThreadIdRoute
  '/clientes/$id': typeof AuthenticatedClientesIdRoute
  '/clientes/importar': typeof AuthenticatedClientesImportarRoute
  '/clientes/nuevo': typeof AuthenticatedClientesNuevoRoute
  '/asistente/': typeof AuthenticatedAsistenteIndexRoute
  '/clientes/': typeof AuthenticatedClientesIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/oportunidades': typeof AuthenticatedOportunidadesRoute
  '/api/chat': typeof ApiChatRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/sectores': typeof AuthenticatedAdminSectoresRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/asistente/$threadId': typeof AuthenticatedAsistenteThreadIdRoute
  '/clientes/$id': typeof AuthenticatedClientesIdRoute
  '/clientes/importar': typeof AuthenticatedClientesImportarRoute
  '/clientes/nuevo': typeof AuthenticatedClientesNuevoRoute
  '/asistente': typeof AuthenticatedAsistenteIndexRoute
  '/clientes': typeof AuthenticatedClientesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/agenda': typeof AuthenticatedAgendaRoute
  '/_authenticated/asistente': typeof AuthenticatedAsistenteRouteWithChildren
  '/_authenticated/clientes': typeof AuthenticatedClientesRouteWithChildren
  '/_authenticated/oportunidades': typeof AuthenticatedOportunidadesRoute
  '/api/chat': typeof ApiChatRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/sectores': typeof AuthenticatedAdminSectoresRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/asistente/$threadId': typeof AuthenticatedAsistenteThreadIdRoute
  '/_authenticated/clientes/$id': typeof AuthenticatedClientesIdRoute
  '/_authenticated/clientes/importar': typeof AuthenticatedClientesImportarRoute
  '/_authenticated/clientes/nuevo': typeof AuthenticatedClientesNuevoRoute
  '/_authenticated/asistente/': typeof AuthenticatedAsistenteIndexRoute
  '/_authenticated/clientes/': typeof AuthenticatedClientesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/agenda'
    | '/asistente'
    | '/clientes'
    | '/oportunidades'
    | '/api/chat'
    | '/admin/sectores'
    | '/admin/usuarios'
    | '/asistente/$threadId'
    | '/clientes/$id'
    | '/clientes/importar'
    | '/clientes/nuevo'
    | '/asistente/'
    | '/clientes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/agenda'
    | '/oportunidades'
    | '/api/chat'
    | '/'
    | '/admin/sectores'
    | '/admin/usuarios'
    | '/asistente/$threadId'
    | '/clientes/$id'
    | '/clientes/importar'
    | '/clientes/nuevo'
    | '/asistente'
    | '/clientes'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/agenda'
    | '/_authenticated/asistente'
    | '/_authenticated/clientes'
    | '/_authenticated/oportunidades'
    | '/api/chat'
    | '/_authenticated/'
    | '/_authenticated/admin/sectores'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/asistente/$threadId'
    | '/_authenticated/clientes/$id'
    | '/_authenticated/clientes/importar'
    | '/_authenticated/clientes/nuevo'
    | '/_authenticated/asistente/'
    | '/_authenticated/clientes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/oportunidades': {
      id: '/_authenticated/oportunidades'
      path: '/oportunidades'
      fullPath: '/oportunidades'
      preLoaderRoute: typeof AuthenticatedOportunidadesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/asistente': {
      id: '/_authenticated/asistente'
      path: '/asistente'
      fullPath: '/asistente'
      preLoaderRoute: typeof AuthenticatedAsistenteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agenda': {
      id: '/_authenticated/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AuthenticatedAgendaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes/': {
      id: '/_authenticated/clientes/'
      path: '/'
      fullPath: '/clientes/'
      preLoaderRoute: typeof AuthenticatedClientesIndexRouteImport
      parentRoute: typeof AuthenticatedClientesRoute
    }
    '/_authenticated/asistente/': {
      id: '/_authenticated/asistente/'
      path: '/'
      fullPath: '/asistente/'
      preLoaderRoute: typeof AuthenticatedAsistenteIndexRouteImport
      parentRoute: typeof AuthenticatedAsistenteRoute
    }
    '/_authenticated/clientes/nuevo': {
      id: '/_authenticated/clientes/nuevo'
      path: '/nuevo'
      fullPath: '/clientes/nuevo'
      preLoaderRoute: typeof AuthenticatedClientesNuevoRouteImport
      parentRoute: typeof AuthenticatedClientesRoute
    }
    '/_authenticated/clientes/importar': {
      id: '/_authenticated/clientes/importar'
      path: '/importar'
      fullPath: '/clientes/importar'
      preLoaderRoute: typeof AuthenticatedClientesImportarRouteImport
      parentRoute: typeof AuthenticatedClientesRoute
    }
    '/_authenticated/clientes/$id': {
      id: '/_authenticated/clientes/$id'
      path: '/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof AuthenticatedClientesIdRouteImport
      parentRoute: typeof AuthenticatedClientesRoute
    }
    '/_authenticated/asistente/$threadId': {
      id: '/_authenticated/asistente/$threadId'
      path: '/$threadId'
      fullPath: '/asistente/$threadId'
      preLoaderRoute: typeof AuthenticatedAsistenteThreadIdRouteImport
      parentRoute: typeof AuthenticatedAsistenteRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/sectores': {
      id: '/_authenticated/admin/sectores'
      path: '/admin/sectores'
      fullPath: '/admin/sectores'
      preLoaderRoute: typeof AuthenticatedAdminSectoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedAsistenteRouteChildren {
  AuthenticatedAsistenteThreadIdRoute: typeof AuthenticatedAsistenteThreadIdRoute
  AuthenticatedAsistenteIndexRoute: typeof AuthenticatedAsistenteIndexRoute
}

const AuthenticatedAsistenteRouteChildren: AuthenticatedAsistenteRouteChildren =
  {
    AuthenticatedAsistenteThreadIdRoute: AuthenticatedAsistenteThreadIdRoute,
    AuthenticatedAsistenteIndexRoute: AuthenticatedAsistenteIndexRoute,
  }

const AuthenticatedAsistenteRouteWithChildren =
  AuthenticatedAsistenteRoute._addFileChildren(
    AuthenticatedAsistenteRouteChildren,
  )

interface AuthenticatedClientesRouteChildren {
  AuthenticatedClientesIdRoute: typeof AuthenticatedClientesIdRoute
  AuthenticatedClientesImportarRoute: typeof AuthenticatedClientesImportarRoute
  AuthenticatedClientesNuevoRoute: typeof AuthenticatedClientesNuevoRoute
  AuthenticatedClientesIndexRoute: typeof AuthenticatedClientesIndexRoute
}

const AuthenticatedClientesRouteChildren: AuthenticatedClientesRouteChildren = {
  AuthenticatedClientesIdRoute: AuthenticatedClientesIdRoute,
  AuthenticatedClientesImportarRoute: AuthenticatedClientesImportarRoute,
  AuthenticatedClientesNuevoRoute: AuthenticatedClientesNuevoRoute,
  AuthenticatedClientesIndexRoute: AuthenticatedClientesIndexRoute,
}

const AuthenticatedClientesRouteWithChildren =
  AuthenticatedClientesRoute._addFileChildren(
    AuthenticatedClientesRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgendaRoute: typeof AuthenticatedAgendaRoute
  AuthenticatedAsistenteRoute: typeof AuthenticatedAsistenteRouteWithChildren
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRouteWithChildren
  AuthenticatedOportunidadesRoute: typeof AuthenticatedOportunidadesRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdminSectoresRoute: typeof AuthenticatedAdminSectoresRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgendaRoute: AuthenticatedAgendaRoute,
  AuthenticatedAsistenteRoute: AuthenticatedAsistenteRouteWithChildren,
  AuthenticatedClientesRoute: AuthenticatedClientesRouteWithChildren,
  AuthenticatedOportunidadesRoute: AuthenticatedOportunidadesRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdminSectoresRoute: AuthenticatedAdminSectoresRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
